//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyITap.Net {

public class TapAPICombinePositionInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPICombinePositionInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPICombinePositionInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPICombinePositionInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPICombinePositionInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyITapApiPINVOKE.delete_TapAPICombinePositionInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint PositionStreamID {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_PositionStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_PositionStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public char ServerFlag {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_ServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_ServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_UpperNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_UpperNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CombineStrategy {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CombineStrategy_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CombineStrategy_get(swigCPtr);
      return ret;
    } 
  }

  public string CombineNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CombineNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CombineNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint PositionQty {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_PositionQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_PositionQty_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSide1 {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_OrderSide1_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_OrderSide1_get(swigCPtr);
      return ret;
    } 
  }

  public uint CombineQty1 {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CombineQty1_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CombineQty1_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag1 {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_HedgeFlag1_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_HedgeFlag1_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo2 {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_ContractNo2_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_ContractNo2_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice2 {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_StrikePrice2_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_StrikePrice2_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag2 {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CallOrPutFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CallOrPutFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSide2 {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_OrderSide2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_OrderSide2_get(swigCPtr);
      return ret;
    } 
  }

  public uint CombineQty2 {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CombineQty2_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CombineQty2_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag2 {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_HedgeFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_HedgeFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrencyGroup {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CommodityCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CommodityCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrency {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CommodityCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_CommodityCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountInitialMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_AccountInitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_AccountInitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountMaintenanceMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_AccountMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_AccountMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperInitialMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_UpperInitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_UpperInitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperMaintenanceMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_UpperMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPICombinePositionInfo_UpperMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICombinePositionInfo() : this(EsunnyITapApiPINVOKE.new_TapAPICombinePositionInfo__SWIG_0(), true) {
  }

  public TapAPICombinePositionInfo(TapAPICombinePositionInfo other) : this(EsunnyITapApiPINVOKE.new_TapAPICombinePositionInfo__SWIG_1(TapAPICombinePositionInfo.getCPtr(other)), true) {
    if (EsunnyITapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyITapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
