//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyITap.Net {

public class TapAPICloseInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPICloseInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPICloseInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPICloseInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPICloseInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyITapApiPINVOKE.delete_TapAPICloseInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char CloseSide {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_CloseSide_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_CloseSide_get(swigCPtr);
      return ret;
    } 
  }

  public uint CloseQty {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_CloseQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_CloseQty_get(swigCPtr);
      return ret;
    } 
  }

  public double OpenPrice {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_OpenPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_OpenPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double ClosePrice {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_ClosePrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_ClosePrice_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenMatchNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_OpenMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_OpenMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenMatchDateTime {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_OpenMatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_OpenMatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseMatchNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_CloseMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_CloseMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CloseMatchDateTime {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_CloseMatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_CloseMatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public uint CloseStreamId {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_CloseStreamId_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_CloseStreamId_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrencyGroup {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_CommodityCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_CommodityCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrency {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_CommodityCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_CommodityCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfit {
    set {
      EsunnyITapApiPINVOKE.TapAPICloseInfo_CloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPICloseInfo_CloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICloseInfo() : this(EsunnyITapApiPINVOKE.new_TapAPICloseInfo__SWIG_0(), true) {
  }

  public TapAPICloseInfo(TapAPICloseInfo other) : this(EsunnyITapApiPINVOKE.new_TapAPICloseInfo__SWIG_1(TapAPICloseInfo.getCPtr(other)), true) {
    if (EsunnyITapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyITapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
