//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyITap.Net {

public class TapAPIHisFundQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIHisFundQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIHisFundQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIHisFundQryRsp obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIHisFundQryRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyITapApiPINVOKE.delete_TapAPIHisFundQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string Date {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Date_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Date_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyGroupNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CurrencyGroupNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CurrencyGroupNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public double PreBalance {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreBalance_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreBalance_get(swigCPtr);
      return ret;
    } 
  }

  public double PreUnExpProfit {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreUnExpProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreUnExpProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double PreLMEPositionProfit {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreLMEPositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreLMEPositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double PreEquity {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreEquity_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreEquity_get(swigCPtr);
      return ret;
    } 
  }

  public double PreAvailable1 {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreAvailable1_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreAvailable1_get(swigCPtr);
      return ret;
    } 
  }

  public double PreAvailable2 {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreAvailable2_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreAvailable2_get(swigCPtr);
      return ret;
    } 
  }

  public double PreMarketEquity {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreMarketEquity_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PreMarketEquity_get(swigCPtr);
      return ret;
    } 
  }

  public uint FutureMatchQty {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_FutureMatchQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_FutureMatchQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OptionMatchQty {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_OptionMatchQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_OptionMatchQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint FuturePositionQty {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_FuturePositionQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_FuturePositionQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OptionPositionQty {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_OptionPositionQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_OptionPositionQty_get(swigCPtr);
      return ret;
    } 
  }

  public double FutureTurnover {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_FutureTurnover_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_FutureTurnover_get(swigCPtr);
      return ret;
    } 
  }

  public double CashInValue {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CashInValue_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CashInValue_get(swigCPtr);
      return ret;
    } 
  }

  public double CashOutValue {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CashOutValue_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CashOutValue_get(swigCPtr);
      return ret;
    } 
  }

  public double AdjustValue {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AdjustValue_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AdjustValue_get(swigCPtr);
      return ret;
    } 
  }

  public double CashPledged {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CashPledged_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CashPledged_get(swigCPtr);
      return ret;
    } 
  }

  public double CashSwapIn {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CashSwapIn_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CashSwapIn_get(swigCPtr);
      return ret;
    } 
  }

  public double CashSwapOut {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CashSwapOut_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CashSwapOut_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountFee {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountFee_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountFee_get(swigCPtr);
      return ret;
    } 
  }

  public double ExchangeFee {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_ExchangeFee_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_ExchangeFee_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountDeliveryFee {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountDeliveryFee_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountDeliveryFee_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperFee {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperFee_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperFee_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperDeliveryFee {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperDeliveryFee_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperDeliveryFee_get(swigCPtr);
      return ret;
    } 
  }

  public double NetFee {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_NetFee_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_NetFee_get(swigCPtr);
      return ret;
    } 
  }

  public double PremiumIncome {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PremiumIncome_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PremiumIncome_get(swigCPtr);
      return ret;
    } 
  }

  public double PremiumPay {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PremiumPay_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PremiumPay_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfit {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double DeliveryProfit {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_DeliveryProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_DeliveryProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double UnExpProfit {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UnExpProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UnExpProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double ExpProfit {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_ExpProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_ExpProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double PositionProfit {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_PositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double LmePositionProfit {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_LmePositionProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_LmePositionProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountIntialMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountIntialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountIntialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountMaintenanceMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperInitalMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperInitalMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperInitalMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperMaintenanceMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountFrozenInitialMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountFrozenInitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountFrozenInitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountFrozenMaintenanceMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountFrozenMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountFrozenMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperFrozenInitialMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperFrozenInitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperFrozenInitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperFrozenMaintenanceMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperFrozenMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperFrozenMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double Balance {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Balance_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Balance_get(swigCPtr);
      return ret;
    } 
  }

  public double Equity {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Equity_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Equity_get(swigCPtr);
      return ret;
    } 
  }

  public double Frozen {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Frozen_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Frozen_get(swigCPtr);
      return ret;
    } 
  }

  public double Available1 {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Available1_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Available1_get(swigCPtr);
      return ret;
    } 
  }

  public double Available2 {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Available2_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Available2_get(swigCPtr);
      return ret;
    } 
  }

  public double CanDraw {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CanDraw_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CanDraw_get(swigCPtr);
      return ret;
    } 
  }

  public double SettleRate {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_SettleRate_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_SettleRate_get(swigCPtr);
      return ret;
    } 
  }

  public double Discount {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Discount_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Discount_get(swigCPtr);
      return ret;
    } 
  }

  public double OptionMarketValue {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_OptionMarketValue_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_OptionMarketValue_get(swigCPtr);
      return ret;
    } 
  }

  public double OriginalCashInOut {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_OriginalCashInOut_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_OriginalCashInOut_get(swigCPtr);
      return ret;
    } 
  }

  public double MarketEquity {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_MarketEquity_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_MarketEquity_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountOtherFee {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountOtherFee_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountOtherFee_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperOtherFee {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperOtherFee_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_UpperOtherFee_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountAuthCash {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountAuthCash_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_AccountAuthCash_get(swigCPtr);
      return ret;
    } 
  }

  public double Interest {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Interest_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_Interest_get(swigCPtr);
      return ret;
    } 
  }

  public double CurInterest {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CurInterest_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_CurInterest_get(swigCPtr);
      return ret;
    } 
  }

  public string SettleGroupNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_SettleGroupNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_SettleGroupNo_get(swigCPtr);
      return ret;
    } 
  }

  public string SuperiorAccount {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_SuperiorAccount_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisFundQryRsp_SuperiorAccount_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIHisFundQryRsp() : this(EsunnyITapApiPINVOKE.new_TapAPIHisFundQryRsp__SWIG_0(), true) {
  }

  public TapAPIHisFundQryRsp(TapAPIHisFundQryRsp other) : this(EsunnyITapApiPINVOKE.new_TapAPIHisFundQryRsp__SWIG_1(TapAPIHisFundQryRsp.getCPtr(other)), true) {
    if (EsunnyITapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyITapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
