//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyITap.Net {

public class TapAPISpecialOrderInsertReq : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPISpecialOrderInsertReq(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPISpecialOrderInsertReq obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPISpecialOrderInsertReq obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPISpecialOrderInsertReq() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyITapApiPINVOKE.delete_TapAPISpecialOrderInsertReq(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public char SpecialOrderType {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_SpecialOrderType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_SpecialOrderType_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSource {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_OrderSource_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_OrderSource_get(swigCPtr);
      return ret;
    } 
  }

  public string CombineNo {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_CombineNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_CombineNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderQty {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_OrderQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_OrderQty_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSide1 {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_OrderSide1_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_OrderSide1_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag1 {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_HedgeFlag1_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_HedgeFlag1_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo2 {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_ContractNo2_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_ContractNo2_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice2 {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_StrikePrice2_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_StrikePrice2_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag2 {
    set {
      EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_CallOrPutFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPISpecialOrderInsertReq_CallOrPutFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPISpecialOrderInsertReq() : this(EsunnyITapApiPINVOKE.new_TapAPISpecialOrderInsertReq__SWIG_0(), true) {
  }

  public TapAPISpecialOrderInsertReq(TapAPISpecialOrderInsertReq other) : this(EsunnyITapApiPINVOKE.new_TapAPISpecialOrderInsertReq__SWIG_1(TapAPISpecialOrderInsertReq.getCPtr(other)), true) {
    if (EsunnyITapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyITapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
