//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyITap.Net {

public class TapAPIAccountMarginRentQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIAccountMarginRentQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIAccountMarginRentQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIAccountMarginRentQryRsp obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIAccountMarginRentQryRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyITapApiPINVOKE.delete_TapAPIAccountMarginRentQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char CalculateMode {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_CalculateMode_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_CalculateMode_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyGroupNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_CurrencyGroupNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_CurrencyGroupNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public double InitialMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_InitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_InitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double MaintenanceMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_MaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_MaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SellInitialMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_SellInitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_SellInitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double SellMaintenanceMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_SellMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_SellMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double LockMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_LockMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIAccountMarginRentQryRsp_LockMargin_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIAccountMarginRentQryRsp() : this(EsunnyITapApiPINVOKE.new_TapAPIAccountMarginRentQryRsp__SWIG_0(), true) {
  }

  public TapAPIAccountMarginRentQryRsp(TapAPIAccountMarginRentQryRsp other) : this(EsunnyITapApiPINVOKE.new_TapAPIAccountMarginRentQryRsp__SWIG_1(TapAPIAccountMarginRentQryRsp.getCPtr(other)), true) {
    if (EsunnyITapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyITapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
