//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyITap.Net {

public class TapAPIHisDeliveryQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIHisDeliveryQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIHisDeliveryQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIHisDeliveryQryRsp obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIHisDeliveryQryRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyITapApiPINVOKE.delete_TapAPIHisDeliveryQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string DeliveryDate {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_DeliveryDate_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_DeliveryDate_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenDate {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OpenDate_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OpenDate_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char MatchSource {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_MatchSource_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_MatchSource_get(swigCPtr);
      return ret;
    } 
  }

  public char OpenSide {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OpenSide_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OpenSide_get(swigCPtr);
      return ret;
    } 
  }

  public double OpenPrice {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OpenPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OpenPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double DeliveryPrice {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_DeliveryPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_DeliveryPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint DeliveryQty {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_DeliveryQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_DeliveryQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint FrozenQty {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_FrozenQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_FrozenQty_get(swigCPtr);
      return ret;
    } 
  }

  public string OpenNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OpenNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OpenNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_UpperNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_UpperNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrencyGroupy {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_CommodityCurrencyGroupy_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_CommodityCurrencyGroupy_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrency {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_CommodityCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_CommodityCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double PreSettlePrice {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_PreSettlePrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_PreSettlePrice_get(swigCPtr);
      return ret;
    } 
  }

  public double DeliveryProfit {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_DeliveryProfit_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_DeliveryProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountFrozenInitialMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_AccountFrozenInitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_AccountFrozenInitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountFrozenMaintenanceMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_AccountFrozenMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_AccountFrozenMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperFrozenInitialMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_UpperFrozenInitialMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_UpperFrozenInitialMargin_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperFrozenMaintenanceMargin {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_UpperFrozenMaintenanceMargin_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_UpperFrozenMaintenanceMargin_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountFeeCurrencyGroup {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_AccountFeeCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_AccountFeeCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountFeeCurrency {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_AccountFeeCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_AccountFeeCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountDeliveryFee {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_AccountDeliveryFee_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_AccountDeliveryFee_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperFeeCurrencyGroup {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_UpperFeeCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_UpperFeeCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperFeeCurrency {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_UpperFeeCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_UpperFeeCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperDeliveryFee {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_UpperDeliveryFee_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_UpperDeliveryFee_get(swigCPtr);
      return ret;
    } 
  }

  public char DeliveryMode {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_DeliveryMode_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_DeliveryMode_get(swigCPtr);
      return ret;
    } 
  }

  public string OperatorNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OperatorNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OperatorNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OperateTime {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OperateTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OperateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string SettleGourpNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_SettleGourpNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_SettleGourpNo_get(swigCPtr);
      return ret;
    } 
  }

  public string FutureContractNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_FutureContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_FutureContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OptionStrikePrice {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OptionStrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_OptionStrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public string SuperiorAccount {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_SuperiorAccount_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisDeliveryQryRsp_SuperiorAccount_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIHisDeliveryQryRsp() : this(EsunnyITapApiPINVOKE.new_TapAPIHisDeliveryQryRsp__SWIG_0(), true) {
  }

  public TapAPIHisDeliveryQryRsp(TapAPIHisDeliveryQryRsp other) : this(EsunnyITapApiPINVOKE.new_TapAPIHisDeliveryQryRsp__SWIG_1(TapAPIHisDeliveryQryRsp.getCPtr(other)), true) {
    if (EsunnyITapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyITapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
