//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyITap.Net {

public class TapAPICurrencyInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPICurrencyInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPICurrencyInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPICurrencyInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPICurrencyInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyITapApiPINVOKE.delete_TapAPICurrencyInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string CurrencyNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICurrencyInfo_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICurrencyInfo_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyGroupNo {
    set {
      EsunnyITapApiPINVOKE.TapAPICurrencyInfo_CurrencyGroupNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPICurrencyInfo_CurrencyGroupNo_get(swigCPtr);
      return ret;
    } 
  }

  public double TradeRate {
    set {
      EsunnyITapApiPINVOKE.TapAPICurrencyInfo_TradeRate_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPICurrencyInfo_TradeRate_get(swigCPtr);
      return ret;
    } 
  }

  public double TradeRate2 {
    set {
      EsunnyITapApiPINVOKE.TapAPICurrencyInfo_TradeRate2_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPICurrencyInfo_TradeRate2_get(swigCPtr);
      return ret;
    } 
  }

  public char FutureAlg {
    set {
      EsunnyITapApiPINVOKE.TapAPICurrencyInfo_FutureAlg_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICurrencyInfo_FutureAlg_get(swigCPtr);
      return ret;
    } 
  }

  public char OptionAlg {
    set {
      EsunnyITapApiPINVOKE.TapAPICurrencyInfo_OptionAlg_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPICurrencyInfo_OptionAlg_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPICurrencyInfo() : this(EsunnyITapApiPINVOKE.new_TapAPICurrencyInfo__SWIG_0(), true) {
  }

  public TapAPICurrencyInfo(TapAPICurrencyInfo other) : this(EsunnyITapApiPINVOKE.new_TapAPICurrencyInfo__SWIG_1(TapAPICurrencyInfo.getCPtr(other)), true) {
    if (EsunnyITapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyITapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
