//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyITap.Net {

public class TapAPIAccountCashAdjustQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIAccountCashAdjustQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIAccountCashAdjustQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIAccountCashAdjustQryRsp obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIAccountCashAdjustQryRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyITapApiPINVOKE.delete_TapAPIAccountCashAdjustQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string Date {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_Date_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_Date_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CashAdjustType {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CashAdjustType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CashAdjustType_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyGroupNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CurrencyGroupNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CurrencyGroupNo_get(swigCPtr);
      return ret;
    } 
  }

  public string CurrencyNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CurrencyNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CurrencyNo_get(swigCPtr);
      return ret;
    } 
  }

  public double CashAdjustValue {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CashAdjustValue_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CashAdjustValue_get(swigCPtr);
      return ret;
    } 
  }

  public string CashAdjustRemark {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CashAdjustRemark_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CashAdjustRemark_get(swigCPtr);
      return ret;
    } 
  }

  public string OperateTime {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_OperateTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_OperateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string OperatorNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_OperatorNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_OperatorNo_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountBank {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_AccountBank_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_AccountBank_get(swigCPtr);
      return ret;
    } 
  }

  public string BankAccount {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_BankAccount_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_BankAccount_get(swigCPtr);
      return ret;
    } 
  }

  public char AccountLWFlag {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_AccountLWFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_AccountLWFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string CompanyBank {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CompanyBank_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CompanyBank_get(swigCPtr);
      return ret;
    } 
  }

  public string InternalBankAccount {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_InternalBankAccount_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_InternalBankAccount_get(swigCPtr);
      return ret;
    } 
  }

  public char CompanyLWFlag {
    set {
      EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CompanyLWFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIAccountCashAdjustQryRsp_CompanyLWFlag_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIAccountCashAdjustQryRsp() : this(EsunnyITapApiPINVOKE.new_TapAPIAccountCashAdjustQryRsp__SWIG_0(), true) {
  }

  public TapAPIAccountCashAdjustQryRsp(TapAPIAccountCashAdjustQryRsp other) : this(EsunnyITapApiPINVOKE.new_TapAPIAccountCashAdjustQryRsp__SWIG_1(TapAPIAccountCashAdjustQryRsp.getCPtr(other)), true) {
    if (EsunnyITapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyITapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
