//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyITap.Net {

public class TapAPIExchangeStateInfoQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIExchangeStateInfoQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIExchangeStateInfoQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIExchangeStateInfoQryRsp obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIExchangeStateInfoQryRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyITapApiPINVOKE.delete_TapAPIExchangeStateInfoQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string ExchangeNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeTime {
    set {
      EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_ExchangeTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_ExchangeTime_get(swigCPtr);
      return ret;
    } 
  }

  public char TradingState {
    set {
      EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_TradingState_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_TradingState_get(swigCPtr);
      return ret;
    } 
  }

  public string OperatorNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_OperatorNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_OperatorNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OperateTime {
    set {
      EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_OperateTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIExchangeStateInfoQryRsp_OperateTime_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIExchangeStateInfoQryRsp() : this(EsunnyITapApiPINVOKE.new_TapAPIExchangeStateInfoQryRsp__SWIG_0(), true) {
  }

  public TapAPIExchangeStateInfoQryRsp(TapAPIExchangeStateInfoQryRsp other) : this(EsunnyITapApiPINVOKE.new_TapAPIExchangeStateInfoQryRsp__SWIG_1(TapAPIExchangeStateInfoQryRsp.getCPtr(other)), true) {
    if (EsunnyITapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyITapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
