//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyITap.Net {

public class TapAPIUserTrustDeviceQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIUserTrustDeviceQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIUserTrustDeviceQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIUserTrustDeviceQryRsp obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIUserTrustDeviceQryRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyITapApiPINVOKE.delete_TapAPIUserTrustDeviceQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIUserTrustDeviceQryRsp_UserNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIUserTrustDeviceQryRsp_UserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string LicenseNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIUserTrustDeviceQryRsp_LicenseNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIUserTrustDeviceQryRsp_LicenseNo_get(swigCPtr);
      return ret;
    } 
  }

  public string Mac {
    set {
      EsunnyITapApiPINVOKE.TapAPIUserTrustDeviceQryRsp_Mac_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIUserTrustDeviceQryRsp_Mac_get(swigCPtr);
      return ret;
    } 
  }

  public string DeviceName {
    set {
      EsunnyITapApiPINVOKE.TapAPIUserTrustDeviceQryRsp_DeviceName_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIUserTrustDeviceQryRsp_DeviceName_get(swigCPtr);
      return ret;
    } 
  }

  public string OperatorNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIUserTrustDeviceQryRsp_OperatorNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIUserTrustDeviceQryRsp_OperatorNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OperateTime {
    set {
      EsunnyITapApiPINVOKE.TapAPIUserTrustDeviceQryRsp_OperateTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIUserTrustDeviceQryRsp_OperateTime_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIUserTrustDeviceQryRsp() : this(EsunnyITapApiPINVOKE.new_TapAPIUserTrustDeviceQryRsp__SWIG_0(), true) {
  }

  public TapAPIUserTrustDeviceQryRsp(TapAPIUserTrustDeviceQryRsp other) : this(EsunnyITapApiPINVOKE.new_TapAPIUserTrustDeviceQryRsp__SWIG_1(TapAPIUserTrustDeviceQryRsp.getCPtr(other)), true) {
    if (EsunnyITapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyITapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
