//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace EsunnyITap.Net {

public class TapAPIHisOrderQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIHisOrderQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIHisOrderQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIHisOrderQryRsp obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIHisOrderQryRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EsunnyITapApiPINVOKE.delete_TapAPIHisOrderQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string Date {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_Date_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_Date_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo2 {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ContractNo2_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ContractNo2_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice2 {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_StrikePrice2_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_StrikePrice2_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag2 {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_CallOrPutFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_CallOrPutFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderType {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSource {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderSource_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderSource_get(swigCPtr);
      return ret;
    } 
  }

  public char TimeInForce {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_TimeInForce_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_TimeInForce_get(swigCPtr);
      return ret;
    } 
  }

  public string ExpireTime {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ExpireTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ExpireTime_get(swigCPtr);
      return ret;
    } 
  }

  public char IsRiskOrder {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_IsRiskOrder_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_IsRiskOrder_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSide {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderSide_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderSide_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_PositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_PositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect2 {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_PositionEffect2_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_PositionEffect2_get(swigCPtr);
      return ret;
    } 
  }

  public string InquiryNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_InquiryNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_InquiryNo_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderPrice {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderPrice2 {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderPrice2_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderPrice2_get(swigCPtr);
      return ret;
    } 
  }

  public double StopPrice {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_StopPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_StopPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderQty {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderMinQty {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderMinQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderMinQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderCanceledQty {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderCanceledQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderCanceledQty_get(swigCPtr);
      return ret;
    } 
  }

  public int RefInt {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_RefInt_set(swigCPtr, value);
    } 
    get {
      int ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_RefInt_get(swigCPtr);
      return ret;
    } 
  }

  public double RefDouble {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_RefDouble_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_RefDouble_get(swigCPtr);
      return ret;
    } 
  }

  public string RefString {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_RefString_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_RefString_get(swigCPtr);
      return ret;
    } 
  }

  public char ServerFlag {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderStreamID {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_UpperNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_UpperNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperChannelNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_UpperChannelNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_UpperChannelNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderLocalNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderLocalNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderLocalNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint UpperStreamID {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_UpperStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_UpperStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderSystemNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderExchangeSystemNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderExchangeSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderExchangeSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderParentSystemNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderParentSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderParentSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderInsertUserNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderInsertUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderInsertUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderInsertTime {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderInsertTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderInsertTime_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderCommandUserNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderCommandUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderCommandUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderUpdateUserNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderUpdateUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderUpdateUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderUpdateTime {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderUpdateTime_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderUpdateTime_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderState {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderState_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderState_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderMatchPrice {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderMatchPrice_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderMatchPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderMatchPrice2 {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderMatchPrice2_set(swigCPtr, value);
    } 
    get {
      double ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderMatchPrice2_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderMatchQty {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderMatchQty_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderMatchQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderMatchQty2 {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderMatchQty2_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_OrderMatchQty2_get(swigCPtr);
      return ret;
    } 
  }

  public uint ErrorCode {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ErrorCode_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ErrorCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorText {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ErrorText_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_ErrorText_get(swigCPtr);
      return ret;
    } 
  }

  public char IsBackInput {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_IsBackInput_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_IsBackInput_get(swigCPtr);
      return ret;
    } 
  }

  public char IsDeleted {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_IsDeleted_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_IsDeleted_get(swigCPtr);
      return ret;
    } 
  }

  public char IsAddOne {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_IsAddOne_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_IsAddOne_get(swigCPtr);
      return ret;
    } 
  }

  public char AddOneIsValid {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_AddOneIsValid_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_AddOneIsValid_get(swigCPtr);
      return ret;
    } 
  }

  public uint MinClipSize {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_MinClipSize_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_MinClipSize_get(swigCPtr);
      return ret;
    } 
  }

  public uint MaxClipSize {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_MaxClipSize_set(swigCPtr, value);
    } 
    get {
      uint ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_MaxClipSize_get(swigCPtr);
      return ret;
    } 
  }

  public string LicenseNo {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_LicenseNo_set(swigCPtr, value);
    } 
    get {
      string ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_LicenseNo_get(swigCPtr);
      return ret;
    } 
  }

  public char TacticsType {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_TacticsType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_TacticsType_get(swigCPtr);
      return ret;
    } 
  }

  public char TriggerCondition {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_TriggerCondition_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_TriggerCondition_get(swigCPtr);
      return ret;
    } 
  }

  public char TriggerPriceType {
    set {
      EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_TriggerPriceType_set(swigCPtr, value);
    } 
    get {
      char ret = EsunnyITapApiPINVOKE.TapAPIHisOrderQryRsp_TriggerPriceType_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIHisOrderQryRsp() : this(EsunnyITapApiPINVOKE.new_TapAPIHisOrderQryRsp__SWIG_0(), true) {
  }

  public TapAPIHisOrderQryRsp(TapAPIHisOrderQryRsp other) : this(EsunnyITapApiPINVOKE.new_TapAPIHisOrderQryRsp__SWIG_1(TapAPIHisOrderQryRsp.getCPtr(other)), true) {
    if (EsunnyITapApiPINVOKE.SWIGPendingException.Pending) throw EsunnyITapApiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
